### ISSUE TITLE
Porting Switch to mobile platforms

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/Switch#1]
**TODO:**

- [ ] Embedding virtual joystick and <kbd>space</kbd> key button.
- [ ] Mapping/Binding the joystick events to `keypress.js`
- [x] Resizing the Canvas
